import { 
  LayoutDashboard, 
  FolderKanban, 
  LayoutTemplate, 
  Wrench, 
  Users, 
  Code2, 
  Shield, 
  Download,
  Image as ImageIcon,
  Video as VideoIcon,
  FileText
} from 'lucide-react';
import { MenuItem } from './types';

export const LOCALE = {
  zh: {
    login: '登录',
    username: '用户名',
    password: '密码',
    welcome: '欢迎回来',
    loginDesc: '登录星云低代码管理平台',
    dashboard: '工作台',
    projects: '项目管理',
    templates: '模板管理',
    resources: '开发资源',
    departments: '部门管理',
    developers: '开发者管理',
    roles: '权限角色',
    downloads: '资源下载',
    imageEditor: 'AI 图片编辑',
    videoGenerator: 'Veo 视频生成',
    theme: '主题',
    language: '语言',
    tenant: '帐套',
    logout: '退出登录',
    quickStart: '快速上手',
    tutorialVideos: '教学视频',
    documentation: '平台文档',
    systemStatus: '系统状态',
    recentActivity: '最近动态',
    uploadImage: '上传图片',
    generate: '生成',
    promptPlaceholder: '描述您想要进行的修改...',
    videoPromptPlaceholder: '描述视频内容 (可选)...',
    loading: '处理中...',
    selectKey: '选择 API Key',
    apiKeyRequired: '需要 API Key 才能继续',
    billingInfo: '需要使用付费项目的 API Key。',
    veoDescription: '上传图片并生成 16:9 或 9:16 的视频。',
    editorDescription: '使用文字指令编辑图片内容。',
    recentProjects: '最近项目',
    createProject: '创建项目',
    importProject: '导入项目',
    userManual: '使用手册',
    trainingVideos: '培训视频',
    quickActions: '快速开始',
    viewAll: '查看全部',
    lastEdited: '最后编辑',
    status: '状态',
    helpCenter: '帮助中心',
    videoDuration: '时长',
    newcomerGuide: '新人向导',
    newcomerGuideDesc: '全方位平台入门指南',
    searchProjects: '搜索项目...',
    noProjectsFound: '未找到匹配的项目',
    pushToGithub: '推送到 GitHub',
    syncing: '同步中...',
    synced: '已同步',
    productManual: '产品使用手册',
    productBlog: '产品功能博客',
    // Project Management
    totalProjects: '项目总数',
    activeProjects: '进行中',
    completedProjects: '已关闭',
    viewGrid: '网格视图',
    viewList: '列表视图',
    members: '成员',
    owner: '负责人',
    actions: '操作',
    edit: '编辑',
    copy: '复制',
    copyConfirm: '确定要复制这个项目吗？',
    delete: '删除',
    deleteConfirm: '确定要删除这个项目吗？',
    filterAll: '全部',
    statusInProgress: '进行中',
    statusClosed: '关闭',
    projectNumber: '项目编号',
    projectNumberPlaceholder: '请输入项目编号 (例如: P-2024-001)',
    // Department Management
    deptName: '部门名称',
    deptCode: '部门编码',
    deptManager: '负责人',
    deptMembers: '成员数',
    deptStatus: '状态',
    deptDesc: '描述',
    parentDepartment: '上级部门',
    rootDepartment: '根节点 (无上级)',
    createDepartment: '新建部门',
    editDepartment: '编辑部门',
    deleteDepartment: '删除部门',
    deptStatusActive: '启用',
    deptStatusInactive: '停用',
    deptCreatedSuccess: '部门创建成功',
    deptUpdatedSuccess: '部门更新成功',
    deptDeletedSuccess: '部门删除成功',
    confirmDeleteDept: '确定要删除该部门吗？',
    managerPlaceholder: '请选择负责人',
    searchDepartments: '搜索部门...',
    noDepartmentsFound: '未找到匹配的部门',
    enterDeptName: '请输入部门名称',
    enterDeptCode: '请输入部门编码',
    save: '保存',
    // Developer Management
    devName: '姓名',
    devPhone: '手机号码',
    devEmail: '邮箱',
    devPosition: '职务',
    devRole: '角色',
    devDept: '所属部门',
    devGender: '性别',
    devAvatar: '头像',
    devBirthday: '生日',
    devStatus: '状态',
    devRemarks: '备注',
    createDeveloper: '添加开发者',
    editDeveloper: '编辑开发者',
    deleteDeveloper: '删除开发者',
    confirmDeleteDev: '确定要删除该开发者吗？',
    male: '男',
    female: '女',
    searchDevelopers: '搜索开发者...',
    noDevelopersFound: '未找到匹配的开发者',
    enterDevName: '请输入姓名',
    enterDevPhone: '请输入手机号码',
    enterDevEmail: '请输入邮箱',
    enterDevPosition: '请输入职务',
    selectDevRole: '选择角色',
    selectDevDept: '选择部门',
    selectDevGender: '选择性别',
    selectDevStatus: '选择状态',
    selectAvatar: '选择头像',
    devJoined: '入职日期',
    // Wizard Translations
    step1: '基础信息',
    step2: '模板选择',
    step3: '数据库配置',
    step4: '确认信息',
    createProjectTitle: '新建项目',
    createProjectSubtitle: '请按照引导步骤设置您的新项目，您可以在任意步骤返回修改',
    projectName: '项目名称',
    projectDesc: '项目描述',
    projectPath: '项目保存路径',
    projectType: '项目类型',
    typeWeb: 'Web应用',
    typeMobile: '移动应用',
    typeDesktop: '桌面应用',
    next: '下一步',
    prev: '上一步',
    create: '立即创建',
    cancel: '取消',
    selectTemplate: '选择应用模板',
    selectTemplateTitle: 'Select Project Template',
    selectTemplateDesc: '选择一个模板可以快速开始您的项目，模板包含了预置的组件和布局。',
    dbType: '数据库类型',
    dbConnection: '连接字符串',
    confirmTitle: '请确认项目信息',
    successCreated: '项目创建成功！',
    emptyTemplate: '空白应用',
    crmTemplate: '基础模板',
    erpTemplate: '高级模板',
    cmsTemplate: 'MES项目',
    // Database Configuration
    dbConfigTitle: '数据库连接配置',
    dbConfigDesc: '选择项目使用的数据库类型，并配置连接信息。',
    dbHost: '数据库主机',
    dbPort: '数据库端口',
    dbName: '数据库名称',
    dbUser: '用户名',
    dbPassword: '密码',
    dbTestConnection: '创建后测试数据库连接',
    dbNamePlaceholder: '请输入数据库名称',
    dbUserPlaceholder: '请输入数据库用户名',
    dbPasswordPlaceholder: '请输入数据库密码',
    // Template Descriptions
    emptyTemplateDesc: '从头开始创建项目，完全自定义。',
    crmTemplateDesc: '包含基础用户体系、权限管理和后台布局，适合快速构建管理系统。',
    erpTemplateDesc: '集成复杂的工作流引擎和多级审批流程，适合企业级业务管理。',
    cmsTemplateDesc: '完整的工业制造执行系统，包含生产计划、质检、库存等核心模块。',
    namePlaceholder: '请输入项目名称',
    descPlaceholder: '请输入项目描述...',
    pathPlaceholder: '/projects/',
    // Edit Modal
    editProjectTitle: '编辑项目',
    editProjectSubtitle: 'Modify project details, status, and member configuration.',
    saveChanges: 'Save Changes',
    saving: '保存中...',
    projectMembers: 'Project Members',
    selectMembers: 'Select Members',
    loadingMembers: 'Loading members...',
    manageMembers: 'Manage Members',
    // Delete Wizard
    deleteProjectTitle: '删除项目',
    deleteProjectSubtitle: '此操作不可逆，请仔细确认要删除的内容',
    warningTitle: '警告：删除操作不可撤销',
    warningDesc: '删除项目将永久移除相关资源，请谨慎操作。建议在删除前备份重要数据。',
    confirmDelProject: '确认要删除的项目',
    confirmDelDesc: '请确认以下项目信息，这是您将要删除的项目。',
    delStep1: 'Confirm Project',
    delStep2: '选择删除项',
    delStep3: '最终确认',
    delStep4: '删除进度',
    projectID: '项目ID',
    createTime: '创建时间',
    lastModified: '最后修改',
    projectSize: '项目大小',
    associatedResources: '重要提示：删除此项目将同时删除以下关联资源：',
    resFrontend: '项目所有前端页面和组件',
    resBackend: '后端API接口和数据服务',
    resDb: '项目数据库及所有数据',
    resLogs: '项目部署配置和日志',
    resPerms: '项目团队成员权限设置',
    typeToConfirm: '请输入项目名称以确认删除',
    deleting: '正在删除项目资源...',
    deleteSuccess: '项目删除成功',
    resourcePages: '前端资源 (Pages/Components)',
    resourceAPI: '后端资源 (APIs/Services)',
    resourceDB: '数据库 (Tables/Data)',
    resourceAssets: '静态资源 (Images/Videos)',
    // Delete Step 2
    delSelectComponentsTitle: '选择要删除的组件',
    delSelectComponentsDesc: '您可以选择删除项目的特定部分，或删除整个项目。',
    selectAllComponents: '全选所有组件',
    selectedComponentsCount: '已选择 {count} / 4 个组件',
    compFrontend: '前端页面与组件',
    compFrontendDesc: '项目所有前端页面、页面布局和UI组件',
    compBackend: '后端接口与服务',
    compBackendDesc: 'API接口、业务逻辑、数据服务和中间件',
    compDB: '数据库与数据',
    compDBDesc: '项目数据库、数据表、存储过程和所有数据',
    compConfig: '配置与部署',
    compConfigDesc: '项目配置、环境变量、部署设置和日志文件',
    statPages: '页面',
    statComponents: '组件',
    statApis: 'API接口',
    statServices: 'Services',
    statTables: '数据表',
    statRecords: '数据记录',
    statEnvs: '环境',
    statFiles: '配置文件',
    dangerZone: '危险操作区域',
    deleteBackups: '同时删除项目备份文件 (3个备份，总计 512 MB)',
    deleteLogs: '同时删除所有操作日志和审计记录',
    dangerActionWarning: '这些操作无法撤销，请谨慎选择',
    // Delete Step 3
    delFinalConfirmTitle: '最终确认',
    delFinalConfirmSubtitle: '请仔细检查删除摘要并输入项目名称以确认删除。',
    delSummaryTitle: '删除摘要',
    delSummaryProjectName: '项目名称',
    delSummaryFrontend: '前端页面与组件:',
    delSummaryBackend: '后端接口与服务:',
    delSummaryDatabase: '数据库与数据:',
    delSummaryConfig: '配置与部署:',
    delSummaryBackups: '项目备份文件:',
    delSummaryLogs: '操作日志:',
    delSummarySpace: '预计释放空间:',
    delStatusDelete: '删除',
    delStatusKeep: '保留',
    delFrontendDetails: '(24个页面, 156个组件)',
    delBackendDetails: '(42个API接口, 8个服务)',
    delDbDetails: '(18个数据表, 12,458条记录)',
    delConfigDetails: '(6个环境, 45个配置文件)',
    delFinalWarningTitle: '最终确认',
    delFinalWarningDesc: '为了确认您理解此操作的后果，请输入项目名称 "{name}" 以继续。',
    delInputLabel: '输入项目名称',
    delInputPlaceholder: '请输入项目名称',
    delCheckboxLabel: '我理解此操作不可撤销，并确认要删除上述所有选中的组件',
  }
};

export const MENUS: MenuItem[] = [
  { id: 'dashboard', icon: LayoutDashboard, labelKey: 'dashboard' },
  { id: 'projects', icon: FolderKanban, labelKey: 'projects' },
  { 
    id: 'resources', 
    icon: Wrench, 
    labelKey: 'resources',
    children: [
      { id: 'image-editor', icon: ImageIcon, labelKey: 'imageEditor' },
      { id: 'video-generator', icon: VideoIcon, labelKey: 'videoGenerator' },
    ]
  },
  { id: 'departments', icon: Users, labelKey: 'departments' },
  { id: 'developers', icon: Code2, labelKey: 'developers' },
  { id: 'roles', icon: Shield, labelKey: 'roles' },
  { id: 'downloads', icon: Download, labelKey: 'downloads' },
];

export const MOCK_TENANTS = [
  { id: 't1', name: 'Nebula Corp', logo: 'NC' },
  { id: 't2', name: 'Starship Enterprise', logo: 'SE' },
  { id: 't3', name: 'Mars Colony', logo: 'MC' },
];

export const CHART_DATA = [
  { name: 'Jan', value: 400 },
  { name: 'Feb', value: 300 },
  { name: 'Mar', value: 600 },
  { name: 'Apr', value: 800 },
  { name: 'May', value: 500 },
];

export const MOCK_PROJECTS = [
  { id: 1, number: 'PRJ-2023-0085', name: 'HR Management System', desc: 'Employee onboarding and leave management.', status: 'In Progress', lastEdited: '2023-10-22', color: 'bg-blue-500', size: '245.6 MB', created: '2023-06-15' },
  { id: 2, number: 'PRJ-2024-0102', name: 'Customer CRM', desc: 'Sales pipeline and customer tracking.', status: 'In Progress', lastEdited: '2024-01-15', color: 'bg-purple-500', size: '120.4 MB', created: '2023-12-01' },
  { id: 3, number: 'PRJ-2024-0045', name: 'Inventory Tracker', desc: 'Warehouse stock monitoring dashboard.', status: 'Closed', lastEdited: '2024-02-10', color: 'bg-emerald-500', size: '89.2 MB', created: '2023-11-20' },
  { id: 4, number: 'PRJ-2024-0211', name: 'Marketing Landing Page', desc: 'Campaign landing page for Q4.', status: 'Closed', lastEdited: '2024-03-01', color: 'bg-amber-500', size: '45.1 MB', created: '2024-02-15' },
];

export const MOCK_DEPARTMENTS = [
  { id: 'd1', name: 'Headquarters', code: 'HQ', manager: 'CEO', memberCount: 50, status: 'Active', description: 'Global HQ', parentId: null },
  { id: 'd2', name: 'R&D Center', code: 'RD', manager: 'Alice Smith', memberCount: 30, status: 'Active', description: 'Research & Development', parentId: 'd1' },
  { id: 'd3', name: 'Frontend Team', code: 'RD-FE', manager: 'David Brown', memberCount: 12, status: 'Active', description: 'Web & Mobile', parentId: 'd2' },
  { id: 'd4', name: 'Backend Team', code: 'RD-BE', manager: 'Eva Davis', memberCount: 18, status: 'Active', description: 'Server & Database', parentId: 'd2' },
  { id: 'd5', name: 'Marketing', code: 'MKT', manager: 'Bob Johnson', memberCount: 15, status: 'Active', description: 'Global Marketing', parentId: 'd1' },
  { id: 'd6', name: 'Human Resources', code: 'HR001', manager: 'Carol Williams', memberCount: 5, status: 'Active', description: 'Talent acquisition and employee relations.', parentId: 'd1' },
];

export const MOCK_DEVELOPERS = [
  { id: 'dev1', name: 'Alice Smith', phone: '13812345678', position: 'Frontend Lead', role: 'Admin', departmentId: 'd3', gender: 'Female', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice', birthday: '1990-05-15', email: 'alice@nebula.com', status: 'Active', joinDate: '2021-03-10', remarks: 'Team lead for core platform' },
  { id: 'dev2', name: 'Bob Johnson', phone: '13987654321', position: 'Backend Lead', role: 'Admin', departmentId: 'd4', gender: 'Male', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob', birthday: '1988-11-22', email: 'bob@nebula.com', status: 'Active', joinDate: '2020-07-01', remarks: 'Database expert' },
  { id: 'dev3', name: 'Carol Williams', phone: '13700001111', position: 'HR Manager', role: 'Viewer', departmentId: 'd6', gender: 'Female', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol', birthday: '1992-02-14', email: 'carol@nebula.com', status: 'Active', joinDate: '2022-01-15', remarks: '' },
  { id: 'dev4', name: 'David Brown', phone: '13666668888', position: 'Frontend Developer', role: 'Developer', departmentId: 'd3', gender: 'Male', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David', birthday: '1995-08-30', email: 'david@nebula.com', status: 'Active', joinDate: '2023-05-20', remarks: 'React specialist' },
  { id: 'dev5', name: 'Eva Davis', phone: '13555554444', position: 'Backend Developer', role: 'Developer', departmentId: 'd4', gender: 'Female', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eva', birthday: '1994-12-05', email: 'eva@nebula.com', status: 'Inactive', joinDate: '2022-09-01', remarks: 'Currently on leave' },
];

export const AVATAR_LIST = {
  male: [
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Jack',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Mason',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Harry',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Jacob',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=George',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Oscar',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=William',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Richard',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Joseph',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Charles'
  ],
  female: [
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Isla',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia',
    'https://api.dicebear.com/7.x/avataaars/svg?seed=Grace'
  ],
  animals: [
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Bear',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Cat',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Dog',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Lion',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Tiger',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Panda',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Koala',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Fox',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Rabbit',
    'https://api.dicebear.com/7.x/fun-emoji/svg?seed=Monkey'
  ]
};

export const TRAINING_VIDEOS = [
  { id: 1, title: '前端页面开发', duration: '12:00', url: 'https://www.bilibili.com/video/BV1Nz42187Ng' },
  { id: 2, title: '后端接口开发', duration: '15:30', url: 'https://www.bilibili.com/video/BV1Zx4y1t7M7' },
  { id: 3, title: '数据库连接', duration: '08:45', url: 'https://www.bilibili.com/video/BV1Sf421B7aT' },
  { id: 4, title: '项目部署', duration: '10:20', url: 'https://www.bilibili.com/video/BV1kx4y147md' },
  { id: 5, title: '事件行为配置', duration: '11:15', url: 'https://www.bilibili.com/video/BV12f421B7JC' },
  { id: 6, title: '后端接口调用', duration: '09:50', url: 'https://www.bilibili.com/video/BV1rz421i7Yh' },
  { id: 7, title: '表格基础配置', duration: '14:05', url: 'https://www.bilibili.com/video/BV1cw4m1Y7FP' },
];

export const HELP_LINKS = [
  { id: 1, titleKey: 'productManual', url: 'https://k6mkvxshbd.feishu.cn/docx/HP6kdNvLIo8JHpxbV0HcQd7gnpf' },
  { id: 2, titleKey: 'productBlog', url: 'https://www.xingyunzuo.cn/blog/blog/' },
];

export const MOCK_TEMPLATES = [
  { id: 'blank', nameKey: 'emptyTemplate', descKey: 'emptyTemplateDesc', icon: LayoutTemplate },
  { id: 'crm', nameKey: 'crmTemplate', descKey: 'crmTemplateDesc', icon: Users },
  { id: 'erp', nameKey: 'erpTemplate', descKey: 'erpTemplateDesc', icon: FolderKanban },
  { id: 'cms', nameKey: 'cmsTemplate', descKey: 'cmsTemplateDesc', icon: FileText },
];