import { 
  LayoutDashboard, 
  FolderKanban, 
  LayoutTemplate, 
  Wrench, 
  Users, 
  Code2, 
  Shield, 
  Download,
  Image as ImageIcon,
  Video as VideoIcon,
  FileText
} from 'lucide-react';
import { MenuItem } from './types';

export const LOCALE = {
  zh: {
    login: '登录',
    username: '用户名',
    password: '密码',
    welcome: '欢迎回来',
    loginDesc: '登录星云低代码管理平台',
    dashboard: '工作台',
    projects: '项目管理',
    templates: '模板管理',
    resources: '开发资源',
    departments: '部门管理',
    developers: '开发者管理',
    roles: '权限角色',
    downloads: '资源下载',
    imageEditor: 'AI 图片编辑',
    videoGenerator: 'Veo 视频生成',
    theme: '主题',
    language: '语言',
    tenant: '帐套',
    logout: '退出登录',
    quickStart: '快速上手',
    tutorialVideos: '教学视频',
    documentation: '平台文档',
    systemStatus: '系统状态',
    recentActivity: '最近动态',
    uploadImage: '上传图片',
    generate: '生成',
    promptPlaceholder: '描述您想要进行的修改...',
    videoPromptPlaceholder: '描述视频内容 (可选)...',
    loading: '处理中...',
    selectKey: '选择 API Key',
    apiKeyRequired: '需要 API Key 才能继续',
    billingInfo: '需要使用付费项目的 API Key。',
    veoDescription: '上传图片并生成 16:9 或 9:16 的视频。',
    editorDescription: '使用文字指令编辑图片内容。',
    recentProjects: '最近项目',
    createProject: '创建项目',
    importProject: '导入项目',
    userManual: '使用手册',
    trainingVideos: '培训视频',
    quickActions: '快速开始',
    viewAll: '查看全部',
    lastEdited: '最后编辑',
    status: '状态',
    helpCenter: '帮助中心',
    videoDuration: '时长',
    newcomerGuide: '新人向导',
    newcomerGuideDesc: '全方位平台入门指南',
    searchProjects: '搜索项目...',
    noProjectsFound: '未找到匹配的项目',
    pushToGithub: '推送到 GitHub',
    syncing: '同步中...',
    synced: '已同步',
    productManual: '产品使用手册',
    productBlog: '产品功能博客',
    // Project Management
    totalProjects: '项目总数',
    activeProjects: '进行中',
    completedProjects: '已关闭',
    viewGrid: '网格视图',
    viewList: '列表视图',
    members: '成员',
    owner: '负责人',
    actions: '操作',
    edit: '编辑',
    copy: '复制',
    copyConfirm: '确定要复制这个项目吗？',
    delete: '删除',
    deleteConfirm: '确定要删除这个项目吗？',
    filterAll: '全部',
    statusInProgress: '进行中',
    statusClosed: '关闭',
    projectNumber: '项目编号',
    projectNumberPlaceholder: '请输入项目编号 (例如: P-2024-001)',
    // Wizard Translations
    step1: '基础信息',
    step2: '模板选择',
    step3: '数据库配置',
    step4: '确认信息',
    createProjectTitle: '新建项目',
    createProjectSubtitle: '请按照引导步骤设置您的新项目，您可以在任意步骤返回修改',
    projectName: '项目名称',
    projectDesc: '项目描述',
    projectPath: '项目保存路径',
    projectType: '项目类型',
    typeWeb: 'Web应用',
    typeMobile: '移动应用',
    typeDesktop: '桌面应用',
    next: '下一步',
    prev: '上一步',
    create: '立即创建',
    cancel: '取消',
    selectTemplate: '选择应用模板',
    selectTemplateTitle: 'Select Project Template',
    selectTemplateDesc: '选择一个模板可以快速开始您的项目，模板包含了预置的组件和布局。',
    dbType: '数据库类型',
    dbConnection: '连接字符串',
    confirmTitle: '请确认项目信息',
    successCreated: '项目创建成功！',
    emptyTemplate: '空白应用',
    crmTemplate: '基础模板',
    erpTemplate: '高级模板',
    cmsTemplate: 'MES项目',
    // Database Configuration
    dbConfigTitle: '数据库连接配置',
    dbConfigDesc: '选择项目使用的数据库类型，并配置连接信息。',
    dbHost: '数据库主机',
    dbPort: '数据库端口',
    dbName: '数据库名称',
    dbUser: '用户名',
    dbPassword: '密码',
    dbTestConnection: '创建后测试数据库连接',
    dbNamePlaceholder: '请输入数据库名称',
    dbUserPlaceholder: '请输入数据库用户名',
    dbPasswordPlaceholder: '请输入数据库密码',
    // Template Descriptions
    emptyTemplateDesc: '从头开始创建项目，完全自定义。',
    crmTemplateDesc: '包含基础用户体系、权限管理和后台布局，适合快速构建管理系统。',
    erpTemplateDesc: '集成复杂的工作流引擎和多级审批流程，适合企业级业务管理。',
    cmsTemplateDesc: '完整的工业制造执行系统，包含生产计划、质检、库存等核心模块。',
    namePlaceholder: '请输入项目名称',
    descPlaceholder: '请输入项目描述...',
    pathPlaceholder: '/projects/',
    // Edit Modal
    editProjectTitle: '编辑项目',
    editProjectSubtitle: '修改项目基本信息、状态及成员配置',
    saveChanges: '保存修改',
    saving: '保存中...',
    projectMembers: '项目成员',
    selectMembers: '选择成员',
    loadingMembers: '加载成员列表中...',
    manageMembers: '管理成员',
    // Delete Wizard
    deleteProjectTitle: '删除项目',
    deleteProjectSubtitle: '此操作不可逆，请仔细确认要删除的内容',
    warningTitle: '警告：删除操作不可撤销',
    warningDesc: '删除项目将永久移除相关资源，请谨慎操作。建议在删除前备份重要数据。',
    confirmDelProject: '确认要删除的项目',
    confirmDelDesc: '请确认以下项目信息，这是您将要删除的项目。',
    delStep1: '确认项目',
    delStep2: '选择删除项',
    delStep3: '最终确认',
    delStep4: '删除进度',
    projectID: '项目ID',
    createTime: '创建时间',
    lastModified: '最后修改',
    projectSize: '项目大小',
    associatedResources: '重要提示：删除此项目将同时删除以下关联资源：',
    resFrontend: '项目所有前端页面和组件',
    resBackend: '后端API接口和数据服务',
    resDb: '项目数据库及所有数据',
    resLogs: '项目部署配置和日志',
    resPerms: '项目团队成员权限设置',
    typeToConfirm: '请输入项目名称以确认删除',
    deleting: '正在删除项目资源...',
    deleteSuccess: '项目删除成功',
    resourcePages: '前端资源 (Pages/Components)',
    resourceAPI: '后端资源 (APIs/Services)',
    resourceDB: '数据库 (Tables/Data)',
    resourceAssets: '静态资源 (Images/Videos)',
    // Delete Step 2
    delSelectComponentsTitle: '选择要删除的组件',
    delSelectComponentsDesc: '您可以选择删除项目的特定部分，或删除整个项目。',
    selectAllComponents: '全选所有组件',
    selectedComponentsCount: '已选择 {count} / 4 个组件',
    compFrontend: '前端页面与组件',
    compFrontendDesc: '项目所有前端页面、页面布局和UI组件',
    compBackend: '后端接口与服务',
    compBackendDesc: 'API接口、业务逻辑、数据服务和中间件',
    compDB: '数据库与数据',
    compDBDesc: '项目数据库、数据表、存储过程和所有数据',
    compConfig: '配置与部署',
    compConfigDesc: '项目配置、环境变量、部署设置和日志文件',
    statPages: '页面',
    statComponents: '组件',
    statApis: 'API接口',
    statServices: '服务',
    statTables: '数据表',
    statRecords: '数据记录',
    statEnvs: '环境',
    statFiles: '配置文件',
    dangerZone: '危险操作区域',
    deleteBackups: '同时删除项目备份文件 (3个备份，总计 512 MB)',
    deleteLogs: '同时删除所有操作日志和审计记录',
    dangerActionWarning: '这些操作无法撤销，请谨慎选择',
    // Delete Step 3
    delFinalConfirmTitle: '最终确认',
    delFinalConfirmSubtitle: '请仔细检查删除摘要并输入项目名称以确认删除。',
    delSummaryTitle: '删除摘要',
    delSummaryProjectName: '项目名称',
    delSummaryFrontend: '前端页面与组件:',
    delSummaryBackend: '后端接口与服务:',
    delSummaryDatabase: '数据库与数据:',
    delSummaryConfig: '配置与部署:',
    delSummaryBackups: '项目备份文件:',
    delSummaryLogs: '操作日志:',
    delSummarySpace: '预计释放空间:',
    delStatusDelete: '删除',
    delStatusKeep: '保留',
    delFrontendDetails: '(24个页面, 156个组件)',
    delBackendDetails: '(42个API接口, 8个服务)',
    delDbDetails: '(18个数据表, 12,458条记录)',
    delConfigDetails: '(6个环境, 45个配置文件)',
    delFinalWarningTitle: '最终确认',
    delFinalWarningDesc: '为了确认您理解此操作的后果，请输入项目名称 "{name}" 以继续。',
    delInputLabel: '输入项目名称',
    delInputPlaceholder: '请输入项目名称',
    delCheckboxLabel: '我理解此操作不可撤销，并确认要删除上述所有选中的组件',
  },
  en: {
    login: 'Login',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome Back',
    loginDesc: 'Sign in to Nebula LowCode Admin',
    dashboard: 'Workbench',
    projects: 'Projects',
    templates: 'Templates',
    resources: 'Dev Resources',
    departments: 'Departments',
    developers: 'Developers',
    roles: 'Roles & Perms',
    downloads: 'Downloads',
    imageEditor: 'AI Image Editor',
    videoGenerator: 'Veo Video Gen',
    theme: 'Theme',
    language: 'Language',
    tenant: 'Tenant',
    logout: 'Logout',
    quickStart: 'Quick Start',
    tutorialVideos: 'Tutorial Videos',
    documentation: 'Documentation',
    systemStatus: 'System Status',
    recentActivity: 'Recent Activity',
    uploadImage: 'Upload Image',
    generate: 'Generate',
    promptPlaceholder: 'Describe the changes you want...',
    videoPromptPlaceholder: 'Describe the video content (optional)...',
    loading: 'Processing...',
    selectKey: 'Select API Key',
    apiKeyRequired: 'API Key Required',
    billingInfo: 'A paid project API Key is required.',
    veoDescription: 'Upload an image to generate a 16:9 or 9:16 video.',
    editorDescription: 'Edit images using natural language prompts.',
    recentProjects: 'Recent Projects',
    createProject: 'Create Project',
    importProject: 'Import Project',
    userManual: 'User Manual',
    trainingVideos: 'Training Videos',
    quickActions: 'Quick Start',
    viewAll: 'View All',
    lastEdited: 'Last Edited',
    status: 'Status',
    helpCenter: 'Help Center',
    videoDuration: 'Duration',
    newcomerGuide: 'Newcomer Guide',
    newcomerGuideDesc: 'Comprehensive platform guide',
    searchProjects: 'Search projects...',
    noProjectsFound: 'No matching projects found',
    pushToGithub: 'Push to GitHub',
    syncing: 'Syncing...',
    synced: 'Synced',
    productManual: 'Product User Manual',
    productBlog: 'Product Features Blog',
    // Project Management
    totalProjects: 'Total Projects',
    activeProjects: 'In Progress',
    completedProjects: 'Closed',
    viewGrid: 'Grid View',
    viewList: 'List View',
    members: 'Members',
    owner: 'Owner',
    actions: 'Actions',
    edit: 'Edit',
    copy: 'Copy',
    copyConfirm: 'Are you sure you want to copy this project?',
    delete: 'Delete',
    deleteConfirm: 'Are you sure you want to delete this project?',
    filterAll: 'All',
    statusInProgress: 'In Progress',
    statusClosed: 'Closed',
    projectNumber: 'Project Number',
    projectNumberPlaceholder: 'Enter project number (e.g., P-2024-001)',
    // Wizard Translations
    step1: 'Basic Info',
    step2: 'Template Selection',
    step3: 'DB Config',
    step4: 'Confirmation',
    createProjectTitle: 'Create New Project',
    createProjectSubtitle: 'Follow the steps to setup your new project. You can go back to modify at any step.',
    projectName: 'Project Name',
    projectDesc: 'Description',
    projectPath: 'Save Path',
    projectType: 'Project Type',
    typeWeb: 'Web App',
    typeMobile: 'Mobile App',
    typeDesktop: 'Desktop App',
    next: 'Next',
    prev: 'Previous',
    create: 'Create Now',
    cancel: 'Cancel',
    selectTemplate: 'Select App Template',
    selectTemplateTitle: 'Select Project Template',
    selectTemplateDesc: 'Select a template to kickstart your project with pre-built components and layouts.',
    dbType: 'Database Type',
    dbConnection: 'Connection String',
    confirmTitle: 'Confirm Project Details',
    successCreated: 'Project Created Successfully!',
    emptyTemplate: 'Blank App',
    crmTemplate: 'Basic Template',
    erpTemplate: 'Advanced Template',
    cmsTemplate: 'MES Project',
    // Database Configuration
    dbConfigTitle: 'Database Connection',
    dbConfigDesc: 'Select the database type and configure connection details.',
    dbHost: 'Database Host',
    dbPort: 'Database Port',
    dbName: 'Database Name',
    dbUser: 'Username',
    dbPassword: 'Password',
    dbTestConnection: 'Test connection after creation',
    dbNamePlaceholder: 'Enter database name',
    dbUserPlaceholder: 'Enter username',
    dbPasswordPlaceholder: 'Enter password',
    // Template Descriptions
    emptyTemplateDesc: 'Start from scratch with a completely custom project.',
    crmTemplateDesc: 'Includes basic user system, permissions, and admin layout.',
    erpTemplateDesc: 'Includes workflow engine, approval processes, and reporting.',
    cmsTemplateDesc: 'Manufacturing Execution System with production planning and QA.',
    namePlaceholder: 'Enter project name',
    descPlaceholder: 'Enter description...',
    pathPlaceholder: '/projects/',
    // Edit Modal
    editProjectTitle: 'Edit Project',
    editProjectSubtitle: 'Modify project details, status, and member configuration.',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    projectMembers: 'Project Members',
    selectMembers: 'Select Members',
    loadingMembers: 'Loading members...',
    manageMembers: 'Manage Members',
    // Delete Wizard
    deleteProjectTitle: 'Delete Project',
    deleteProjectSubtitle: 'This action is irreversible, please carefully confirm.',
    warningTitle: 'Warning: Action Cannot Be Undone',
    warningDesc: 'Deleting this project will permanently remove associated resources. Please proceed with caution.',
    confirmDelProject: 'Confirm Project to Delete',
    confirmDelDesc: 'Please review the project information below.',
    delStep1: 'Confirm Project',
    delStep2: 'Select Items',
    delStep3: 'Final Confirm',
    delStep4: 'Progress',
    projectID: 'Project ID',
    createTime: 'Created Time',
    lastModified: 'Last Modified',
    projectSize: 'Size',
    associatedResources: 'Important: Deleting this project will also delete:',
    resFrontend: 'All frontend pages and components',
    resBackend: 'Backend APIs and data services',
    resDb: 'Project database and data',
    resLogs: 'Deployment configs and logs',
    resPerms: 'Team member permissions',
    typeToConfirm: 'Type project name to confirm delete',
    deleting: 'Deleting project resources...',
    deleteSuccess: 'Project Deleted Successfully',
    resourcePages: 'Frontend Resources (Pages/Components)',
    resourceAPI: 'Backend Resources (APIs/Services)',
    resourceDB: 'Database (Tables/Data)',
    resourceAssets: 'Static Assets (Images/Videos)',
    // Delete Step 2
    delSelectComponentsTitle: 'Select Components to Delete',
    delSelectComponentsDesc: 'You can choose to delete specific parts of the project, or delete the entire project.',
    selectAllComponents: 'Select All Components',
    selectedComponentsCount: 'Selected {count} / 4 components',
    compFrontend: 'Frontend Pages & Components',
    compFrontendDesc: 'All project frontend pages, page layouts, and UI components',
    compBackend: 'Backend Interfaces & Services',
    compBackendDesc: 'API interfaces, business logic, data services, and middleware',
    compDB: 'Database & Data',
    compDBDesc: 'Project database, tables, stored procedures, and all data',
    compConfig: 'Configuration & Deployment',
    compConfigDesc: 'Project configuration, env vars, deployment settings, and log files',
    statPages: 'Pages',
    statComponents: 'Components',
    statApis: 'APIs',
    statServices: 'Services',
    statTables: 'Tables',
    statRecords: 'Records',
    statEnvs: 'Envs',
    statFiles: 'Configs',
    dangerZone: 'Danger Zone',
    deleteBackups: 'Also delete project backup files (3 backups, 512 MB total)',
    deleteLogs: 'Also delete all operation logs and audit records',
    dangerActionWarning: 'These actions cannot be undone, please choose carefully',
    // Delete Step 3
    delFinalConfirmTitle: 'Final Confirmation',
    delFinalConfirmSubtitle: 'Please review the deletion summary and enter the project name to confirm.',
    delSummaryTitle: 'Deletion Summary',
    delSummaryProjectName: 'Project Name',
    delSummaryFrontend: 'Frontend Pages & Components:',
    delSummaryBackend: 'Backend Interfaces & Services:',
    delSummaryDatabase: 'Database & Data:',
    delSummaryConfig: 'Configuration & Deployment:',
    delSummaryBackups: 'Project Backups:',
    delSummaryLogs: 'Operation Logs:',
    delSummarySpace: 'Est. Freed Space:',
    delStatusDelete: 'Delete',
    delStatusKeep: 'Keep',
    delFrontendDetails: '(24 Pages, 156 Components)',
    delBackendDetails: '(42 APIs, 8 Services)',
    delDbDetails: '(18 Tables, 12,458 Records)',
    delConfigDetails: '(6 Envs, 45 Config Files)',
    delFinalWarningTitle: 'Final Confirmation',
    delFinalWarningDesc: 'To confirm you understand the consequences, please enter project name "{name}" to continue.',
    delInputLabel: 'Enter Project Name',
    delInputPlaceholder: 'Enter project name',
    delCheckboxLabel: 'I understand this action is irreversible and confirm to delete all selected components.',
  }
};

export const MENUS: MenuItem[] = [
  { id: 'dashboard', icon: LayoutDashboard, labelKey: 'dashboard' },
  { id: 'projects', icon: FolderKanban, labelKey: 'projects' },
  { id: 'templates', icon: LayoutTemplate, labelKey: 'templates' },
  { 
    id: 'resources', 
    icon: Wrench, 
    labelKey: 'resources',
    children: [
      { id: 'image-editor', icon: ImageIcon, labelKey: 'imageEditor' },
      { id: 'video-generator', icon: VideoIcon, labelKey: 'videoGenerator' },
    ]
  },
  { id: 'departments', icon: Users, labelKey: 'departments' },
  { id: 'developers', icon: Code2, labelKey: 'developers' },
  { id: 'roles', icon: Shield, labelKey: 'roles' },
  { id: 'downloads', icon: Download, labelKey: 'downloads' },
];

export const MOCK_TENANTS = [
  { id: 't1', name: 'Nebula Corp', logo: 'NC' },
  { id: 't2', name: 'Starship Enterprise', logo: 'SE' },
  { id: 't3', name: 'Mars Colony', logo: 'MC' },
];

export const CHART_DATA = [
  { name: 'Jan', value: 400 },
  { name: 'Feb', value: 300 },
  { name: 'Mar', value: 600 },
  { name: 'Apr', value: 800 },
  { name: 'May', value: 500 },
];

export const MOCK_PROJECTS = [
  { id: 1, number: 'PRJ-2023-0085', name: 'HR Management System', desc: 'Employee onboarding and leave management.', status: 'In Progress', lastEdited: '2023-10-22', color: 'bg-blue-500', size: '245.6 MB', created: '2023-06-15' },
  { id: 2, number: 'PRJ-2024-0102', name: 'Customer CRM', desc: 'Sales pipeline and customer tracking.', status: 'In Progress', lastEdited: '2024-01-15', color: 'bg-purple-500', size: '120.4 MB', created: '2023-12-01' },
  { id: 3, number: 'PRJ-2024-0045', name: 'Inventory Tracker', desc: 'Warehouse stock monitoring dashboard.', status: 'Closed', lastEdited: '2024-02-10', color: 'bg-emerald-500', size: '89.2 MB', created: '2023-11-20' },
  { id: 4, number: 'PRJ-2024-0211', name: 'Marketing Landing Page', desc: 'Campaign landing page for Q4.', status: 'Closed', lastEdited: '2024-03-01', color: 'bg-amber-500', size: '45.1 MB', created: '2024-02-15' },
];

export const TRAINING_VIDEOS = [
  { id: 1, title: '前端页面开发', duration: '12:00', url: 'https://www.bilibili.com/video/BV1Nz42187Ng' },
  { id: 2, title: '后端接口开发', duration: '15:30', url: 'https://www.bilibili.com/video/BV1Zx4y1t7M7' },
  { id: 3, title: '数据库连接', duration: '08:45', url: 'https://www.bilibili.com/video/BV1Sf421B7aT' },
  { id: 4, title: '项目部署', duration: '10:20', url: 'https://www.bilibili.com/video/BV1kx4y147md' },
  { id: 5, title: '事件行为配置', duration: '11:15', url: 'https://www.bilibili.com/video/BV12f421B7JC' },
  { id: 6, title: '后端接口调用', duration: '09:50', url: 'https://www.bilibili.com/video/BV1rz421i7Yh' },
  { id: 7, title: '表格基础配置', duration: '14:05', url: 'https://www.bilibili.com/video/BV1cw4m1Y7FP' },
];

export const HELP_LINKS = [
  { id: 1, titleKey: 'productManual', url: 'https://k6mkvxshbd.feishu.cn/docx/HP6kdNvLIo8JHpxbV0HcQd7gnpf' },
  { id: 2, titleKey: 'productBlog', url: 'https://www.xingyunzuo.cn/blog/blog/' },
];

export const MOCK_TEMPLATES = [
  { id: 'blank', nameKey: 'emptyTemplate', descKey: 'emptyTemplateDesc', icon: LayoutTemplate },
  { id: 'crm', nameKey: 'crmTemplate', descKey: 'crmTemplateDesc', icon: Users },
  { id: 'erp', nameKey: 'erpTemplate', descKey: 'erpTemplateDesc', icon: FolderKanban },
  { id: 'cms', nameKey: 'cmsTemplate', descKey: 'cmsTemplateDesc', icon: FileText },
];