import { 
  LayoutDashboard, 
  FolderKanban, 
  LayoutTemplate, 
  Wrench, 
  Users, 
  Code2, 
  Shield, 
  Download,
  Image as ImageIcon,
  Video as VideoIcon
} from 'lucide-react';
import { MenuItem } from './types';

export const LOCALE = {
  zh: {
    login: '登录',
    username: '用户名',
    password: '密码',
    welcome: '欢迎回来',
    loginDesc: '登录星云低代码管理平台',
    dashboard: '工作台',
    projects: '项目管理',
    templates: '模板管理',
    resources: '开发资源',
    departments: '部门管理',
    developers: '开发者管理',
    roles: '权限角色',
    downloads: '资源下载',
    imageEditor: 'AI 图片编辑',
    videoGenerator: 'Veo 视频生成',
    theme: '主题',
    language: '语言',
    tenant: '帐套',
    logout: '退出登录',
    quickStart: '快速上手',
    tutorialVideos: '教学视频',
    documentation: '平台文档',
    systemStatus: '系统状态',
    recentActivity: '最近动态',
    uploadImage: '上传图片',
    generate: '生成',
    promptPlaceholder: '描述您想要进行的修改...',
    videoPromptPlaceholder: '描述视频内容 (可选)...',
    loading: '处理中...',
    selectKey: '选择 API Key',
    apiKeyRequired: '需要 API Key 才能继续',
    billingInfo: '需要使用付费项目的 API Key。',
    veoDescription: '上传图片并生成 16:9 或 9:16 的视频。',
    editorDescription: '使用文字指令编辑图片内容。',
    recentProjects: '最近项目',
    createProject: '创建项目',
    importProject: '导入项目',
    userManual: '使用手册',
    trainingVideos: '培训视频',
    quickActions: '快速开始',
    viewAll: '查看全部',
    lastEdited: '最后编辑',
    status: '状态',
    helpCenter: '帮助中心',
    videoDuration: '时长',
    newcomerGuide: '新人向导',
    newcomerGuideDesc: '全方位平台入门指南',
    searchProjects: '搜索项目...',
    noProjectsFound: '未找到匹配的项目',
  },
  en: {
    login: 'Login',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome Back',
    loginDesc: 'Sign in to Nebula LowCode Admin',
    dashboard: 'Workbench',
    projects: 'Projects',
    templates: 'Templates',
    resources: 'Dev Resources',
    departments: 'Departments',
    developers: 'Developers',
    roles: 'Roles & Perms',
    downloads: 'Downloads',
    imageEditor: 'AI Image Editor',
    videoGenerator: 'Veo Video Gen',
    theme: 'Theme',
    language: 'Language',
    tenant: 'Tenant',
    logout: 'Logout',
    quickStart: 'Quick Start',
    tutorialVideos: 'Tutorial Videos',
    documentation: 'Documentation',
    systemStatus: 'System Status',
    recentActivity: 'Recent Activity',
    uploadImage: 'Upload Image',
    generate: 'Generate',
    promptPlaceholder: 'Describe the changes you want...',
    videoPromptPlaceholder: 'Describe the video content (optional)...',
    loading: 'Processing...',
    selectKey: 'Select API Key',
    apiKeyRequired: 'API Key Required',
    billingInfo: 'A paid project API Key is required.',
    veoDescription: 'Upload an image to generate a 16:9 or 9:16 video.',
    editorDescription: 'Edit images using natural language prompts.',
    recentProjects: 'Recent Projects',
    createProject: 'Create Project',
    importProject: 'Import Project',
    userManual: 'User Manual',
    trainingVideos: 'Training Videos',
    quickActions: 'Quick Start',
    viewAll: 'View All',
    lastEdited: 'Last Edited',
    status: 'Status',
    helpCenter: 'Help Center',
    videoDuration: 'Duration',
    newcomerGuide: 'Newcomer Guide',
    newcomerGuideDesc: 'Comprehensive platform guide',
    searchProjects: 'Search projects...',
    noProjectsFound: 'No matching projects found',
  }
};

export const MENUS: MenuItem[] = [
  { id: 'dashboard', icon: LayoutDashboard, labelKey: 'dashboard' },
  { id: 'projects', icon: FolderKanban, labelKey: 'projects' },
  { id: 'templates', icon: LayoutTemplate, labelKey: 'templates' },
  { 
    id: 'resources', 
    icon: Wrench, 
    labelKey: 'resources',
    children: [
      { id: 'image-editor', icon: ImageIcon, labelKey: 'imageEditor' },
      { id: 'video-generator', icon: VideoIcon, labelKey: 'videoGenerator' },
    ]
  },
  { id: 'departments', icon: Users, labelKey: 'departments' },
  { id: 'developers', icon: Code2, labelKey: 'developers' },
  { id: 'roles', icon: Shield, labelKey: 'roles' },
  { id: 'downloads', icon: Download, labelKey: 'downloads' },
];

export const MOCK_TENANTS = [
  { id: 't1', name: 'Nebula Corp', logo: 'NC' },
  { id: 't2', name: 'Starship Enterprise', logo: 'SE' },
  { id: 't3', name: 'Mars Colony', logo: 'MC' },
];

export const CHART_DATA = [
  { name: 'Jan', value: 400 },
  { name: 'Feb', value: 300 },
  { name: 'Mar', value: 600 },
  { name: 'Apr', value: 800 },
  { name: 'May', value: 500 },
];

export const MOCK_PROJECTS = [
  { id: 1, name: 'HR Management System', desc: 'Employee onboarding and leave management.', status: 'Active', lastEdited: '2 mins ago', color: 'bg-blue-500' },
  { id: 2, name: 'Customer CRM', desc: 'Sales pipeline and customer tracking.', status: 'In Progress', lastEdited: '4 hours ago', color: 'bg-purple-500' },
  { id: 3, name: 'Inventory Tracker', desc: 'Warehouse stock monitoring dashboard.', status: 'Review', lastEdited: '1 day ago', color: 'bg-emerald-500' },
  { id: 4, name: 'Marketing Landing Page', desc: 'Campaign landing page for Q4.', status: 'Draft', lastEdited: '2 days ago', color: 'bg-amber-500' },
];

export const TRAINING_VIDEOS = [
  { id: 1, title: 'Getting Started with Nebula', duration: '5:20' },
  { id: 2, title: 'Building your first App', duration: '12:45' },
  { id: 3, title: 'Connecting to Databases', duration: '8:30' },
  { id: 4, title: 'Using AI Features', duration: '4:15' },
];

export const HELP_LINKS = [
  { id: 1, title: 'Platform Overview' },
  { id: 2, title: 'Component Library' },
  { id: 3, title: 'API Documentation' },
  { id: 4, title: 'Best Practices' },
];